// sites.js
var defaultSites = {
  "60 Millions de consommateurs": "60millions-mag.com",
  "Aachener Zeitung (fetch from archive.is)": "aachener-zeitung.de",
  "Abcmais.com": "abcmais.com",
  "Actu.fr": "actu.fr",
  "Adweek": "adweek.com",
  "Al-Monitor (fetch from archive.is)": "al-monitor.com",
  "Albuquerque Journal": "abqjournal.com",
  "Alternatives Economiques": "alternatives-economiques.fr",
  "Ámbito": "ambito.com",
  "America's Test Kitchen": "americastestkitchen.com",
  "American Affairs": "americanaffairsjournal.org",
  "American Banker (+ Arizent/opt-in to custom sites)": "americanbanker.com",
  "American Purpose": "americanpurpose.com",
  "Aoc.media": "aoc.media",
  "Artforum": "artforum.com",
  "Artnet": "artnet.com",
  "Ärzte Zeitung": "aerztezeitung.de",
  "Atavist Magazine": "atavist.com",
  "Atlantico.fr": "atlantico.fr",
  "Autocar.co.uk": "autocar.co.uk",
  "AutoHebdo.fr": "autohebdo.fr",
  "Automobilwoche": "automobilwoche.de",
  "AutoPlus.fr": "autoplus.fr",
  "Autosport (free articles only)": "autosport.com",
  "Axios": "axios.com",
  "Badische Neueste Nachrichten (fetch from archive.is)": "bnn.de",
  "Balkan Insight": "balkaninsight.com",
  "Bar and Bench": "barandbench.com",
  "Barron's": "barrons.com",
  "BBC History Extra": "historyextra.com",
  "BBC USA": "bbc.com",
  "Benzinga": "benzinga.com",
  "Bergens Tidende": "bt.no",
  "Berliner Zeitung (fetch from archive.is)": "berliner-zeitung.de",
  "Bhaskar": "bhaskar.com",
  "Bild (fetch from archive.is)": "bild.de",
  "Blaze Media": "theblaze.com",
  "Bloomberg (not Terminal)": "bloomberg.com",
  "Bloomberg Adria": "bloombergadria.com",
  "Börsen-Zeitung": "boersen-zeitung.de",
  "Bulletin of the Atomic Scientists": "thebulletin.org",
  "BusinessAM.be": "businessam.be",
  "BusinessDesk.co.nz": "businessdesk.co.nz",
  "Business Insider": "businessinsider.com",
  "Business Insider Japan": "businessinsider.jp",
  "Business Insider Nederland": "businessinsider.nl",
  "Business Post.ie": "businesspost.ie",
  "Business Standard": "business-standard.com",
  "Capital.bg": "capital.bg",
  "Capital.fr": "capital.fr",
  "CaravanMagazine.in (fetch from archive.is)": "caravanmagazine.in",
  "CartaCapital": "cartacapital.com.br",
  "Causeur": "causeur.fr",
  "Challenges": "challenges.fr",
  "Charlie Hebdo": "charliehebdo.fr",
  "Chemical & Engineering News": "cen.acs.org",
  "Chicago Sun-Times": "chicago.suntimes.com",
  "Cicero.de (fetch from archive.is)": "cicero.de",
  "Citeline Insights": "insights.citeline.com",
  "Citywire": "citywire.com",
  "CNBC (news only)": "cnbc.com",
  "CNN": "cnn.com",
  "Commentary Magazine": "commentary.org",
  "CommonWealth Magazine Taiwan (free articles only)": "cw.com.tw",
  "Connaissance des Arts": "connaissancedesarts.com",
  "Correio do Povo": "correiodopovo.com.br",
  "Corriere della Sera": "corriere.it",
  "Corriere dello Sport": "corrieredellosport.it",
  "Cosmopolitan.fr": "cosmopolitan.fr",
  "Courrier international": "courrierinternational.com",
  "Crusoe.com.br": "crusoe.com.br",
  "CyclingNews": "cyclingnews.com",
  "Dagsavisen.no": "dagsavisen.no",
  "Daily Herald (USA)": "dailyherald.com",
  "De Tijd": "tijd.be",
  "Decanter (not reviews)": "decanter.com",
  "Defector": "defector.com",
  "Denik.cz": "denik.cz",
  "Der Freitag": "freitag.de",
  "Der Spiegel (fetch from archive.is)": "spiegel.de",
  "Der Standard.at": "derstandard.at",
  "Der Tagesspiegel (fetch from archive.is; not background/checkpoint)": "tagesspiegel.de",
  "Diario de Navarra (text only)": "diariodenavarra.es",
  "Diário de Notícias (dn.pt)": "dn.pt",
  "Diario Financiero (df.cl)": "df.cl",
  "Die Presse (AT)": "diepresse.com",
  "Die Rheinpfalz": "rheinpfalz.de",
  "Die Welt (fetch from archive.is)": "welt.de",
  "Die Zeit (fetch from archive.is)": "zeit.de",
  "Discover Magazine": "discovermagazine.com",
  "Dnevnik.bg": "dnevnik.bg",
  "Domani": "editorialedomani.it",
  "Doorbraak.be": "doorbraak.be",
  "Dwell": "dwell.com",
  "Eastwest.eu": "eastwest.eu",
  "El Confidencial": "elconfidencial.com",
  "El Cronista": "cronista.com",
  "El Deber.com.bo": "eldeber.com.bo",
  "El Diario.es": "eldiario.es",
  "El Español": "elespanol.com",
  "El Espectador": "elespectador.com",
  "El Mercurio (digital only)": "elmercurio.com",
  "El Observador.com.uy": "elobservador.com.uy",
  "El País": "elpais.com",
  "El País.com.uy": "elpais.com.uy",
  "El Tiempo (CO)": "eltiempo.com",
  "El Tribuno (AR)": "eltribuno.com",
  "El Universal.com.mx": "eluniversal.com.mx",
  "El Universo (EC)": "eluniverso.com",
  "Elle.fr": "elle.fr",
  "Encyclopedia Britannica": "britannica.com",
  "eNotes": "enotes.com",
  "Entrepreneur": "entrepreneur.com",
  "ESPN USA (news only; fetch from archive.is)": "espn.com",
  "Esprit": "esprit.presse.fr",
  "Estado de Minas": "em.com.br",
  "EUobserver": "euobserver.com",
  "Evening Standard (UK)": "standard.co.uk",
  "Exame": "exame.com",
  "Expresso.pt (not Tribuna)": "expresso.pt",
  "Fast Company": "fastcompany.com",
  "Field & Stream": "fieldandstream.com",
  "Financial News (London)": "fnlondon.com",
  "Financial Times (not cn subdomain)": "ft.com",
  "First Things": "firstthings.com",
  "FMR": "fmrmagazine.com",
  "FocusPlus.de": "focusplus.de",
  "Fokus.se": "fokus.se",
  "Forbes (not newsletters)": "forbes.com",
  "Forbes Australia": "forbes.com.au",
  "Forbes.ua (text only)": "forbes.ua",
  "Foreign Affairs (not reader)": "foreignaffairs.com",
  "Foreign Policy": "foreignpolicy.com",
  "Fortune": "fortune.com",
  "Fox News (regwall)": "foxnews.com",
  "Franc-Tireur.fr": "franc-tireur.fr",
  "Frankfurter Allgemeine Zeitung (not rechner)": "faz.net",
  "Freie Presse.de (no charts; fetch from archive.is)": "freiepresse.de",
  "GaúchaZH": "gauchazh.clicrbs.com.br",
  "Gazeta do Povo": "gazetadopovo.com.br",
  "GB News": "gbnews.com",
  "Glassdoor (regwall)": "glassdoor.com",
  "Globes": "globes.co.il",
  "Granta Magazine": "granta.com",
  "Groene Amsterdammer": "groene.nl",
  "Grupo Abril": "abril.com.br",
  "Handelsblatt": "handelsblatt.com",
  "Harper's Magazine (free articles only)": "harpers.org",
  "Harvard Business Review (do not block TinyPass-script externally)": "hbr.org",
  "Heise online (fetch from archive.is)": "heise.de",
  "Het Laatste Nieuws (fetch from archive.is)": "hln.be",
  "Hindustan Times (not epaper)": "hindustantimes.com",
  "Historia.fr": "historia.fr",
  "History Today (app only)": "historytoday.com",
  "Hola": "hola.com",
  "Honolulu Star-Advertiser": "staradvertiser.com",
  "Il Fatto Quotidiano (free articles only)": "ilfattoquotidiano.it",
  "Il Foglio": "ilfoglio.it",
  "Il Manifesto": "ilmanifesto.it",
  "Il Sole 24 Ore (24+ only)": "ilsole24ore.com",
  "Inc.com": "inc.com",
  "Inc42": "inc42.com",
  "India Today": "indiatoday.in",
  "iNews (UK)": "inews.co.uk",
  "InfoLibre.es": "infolibre.es",
  "Inkl": "inkl.com",
  "Inside Higher Ed": "insidehighered.com",
  "Institute of Art and Ideas (articles only)": "iai.tv",
  "Interesting Engineering": "interestingengineering.com",
  "Internazionale.it": "internazionale.it",
  "Investor's Business Daily": "investors.com",
  "Investors' Chronicle (UK)": "investorschronicle.co.uk",
  "iPolitics.ca": "ipolitics.ca",
  "Italia Oggi": "italiaoggi.it",
  "Jacobin.de": "jacobin.de",
  "Jazzwise": "jazzwise.com",
  "Jeune Afrique (last month only)": "jeuneafrique.com",
  "Kathimerini.gr": "kathimerini.gr",
  "Kleine Zeitung.at": "kleinezeitung.at",
  "Kölner Stadt-Anzeiger": "ksta.de",
  "Kölnische Rundschau": "rundschau-online.de",
  "Kompas.id": "kompas.id",
  "Krautreporter.de": "krautreporter.de",
  "Kurier.at": "kurier.at",
  "L'Écho": "lecho.be",
  "L'Équipe.fr": "lequipe.fr",
  "L'Express": "lexpress.fr",
  "L'Informé (not pro)": "linforme.com",
  "L'Oeil de la Photographie": "loeildelaphotographie.com",
  "L'Opinion (not Le Journal)": "lopinion.fr",
  "La Croix": "la-croix.com",
  "La Diaria.com.uy": "ladiaria.com.uy",
  "La Gaceta.com.ar (no menu)": "lagaceta.com.ar",
  "La Gazzetta dello Sport (text only)": "gazzetta.it",
  "La Nación": "lanacion.com.ar",
  "La Segunda (not digital)": "lasegunda.com",
  "La Tercera": "latercera.com",
  "La Vanguardia": "lavanguardia.com",
  "Lance.com.br": "lance.com.br",
  "Las Vegas Review-Journal": "reviewjournal.com",
  "Law.com (not archive)": "law.com",
  "Le Canard enchaîné.fr": "lecanardenchaine.fr",
  "Le Courrier des Stratèges": "lecourrierdesstrateges.fr",
  "Le Devoir": "ledevoir.com",
  "Le Figaro (no video)": "lefigaro.fr",
  "Le Grand Continent": "legrandcontinent.eu",
  "Le Journal du Dimanche": "lejdd.fr",
  "Le Journal du Net": "journaldunet.com",
  "Le Monde.fr": "lemonde.fr",
  "Le Monde Diplomatique Brasil": "diplomatique.org.br",
  "Le Nouvel Economiste": "lenouveleconomiste.fr",
  "Le Parisien": "leparisien.fr",
  "Le Point": "lepoint.fr",
  "Le Revenu": "lerevenu.com",
  "Le Temps.ch (fetch from archive.is)": "letemps.ch",
  "Le1Hebdo.fr": "le1hebdo.fr",
  "Les Échos": "lesechos.fr",
  "Les Inrockuptibles": "lesinrocks.com",
  "Libération.fr": "liberation.fr",
  "Linda.nl": "linda.nl",
  "Literary Review (UK)": "literaryreview.co.uk",
  "Live Law": "livelaw.in",
  "LiveMint (not epaper)": "livemint.com",
  "Loeb Classical Library": "loebclassics.com",
  "London Review of Books": "lrb.co.uk",
  "Los Angeles Times": "latimes.com",
  "MacroBusiness.com.au": "macrobusiness.com.au",
  "Malayala Manorama": "manoramaonline.com",
  "MarketWatch": "marketwatch.com",
  "Medscape (regwall)": "medscape.com",
  "Mexico News Daily": "mexiconewsdaily.com",
  "Mid-Day (not epaper)": "mid-day.com",
  "MilanoFinanza.it": "milanofinanza.it",
  "Milenio": "milenio.com",
  "MIT Sloan Management Review": "sloanreview.mit.edu",
  "MIT Technology Review": "technologyreview.com",
  "Mittelbayerische Zeitung (fetch from archive.is)": "mittelbayerische.de",
  "Monocle": "monocle.com",
  "Motor Sport Magazine (UK)": "motorsportmagazine.com",
  "Mountain View Voice": "mv-voice.com",
  "Mundo Deportivo": "mundodeportivo.com",
  "MusicOMH": "musicomh.com",
  "National Geographic ES": "nationalgeographic.com.es",
  "National Geographic IT": "nationalgeographic.it",
  "National Geographic NL": "nationalgeographic.nl",
  "National Geographic USA": "nationalgeographic.com",
  "National Review": "nationalreview.com",
  "Nautilus": "nautil.us",
  "Nature (regwall only; fetch from archive.is)": "nature.com",
  "NBC News": "nbcnews.com",
  "NDTV Profit": "ndtvprofit.com",
  "Neue Westfälische": "nw.de",
  "Neue Zürcher Zeitung": "nzz.ch",
  "New Scientist": "newscientist.com",
  "New Voice (nv.ua)": "nv.ua",
  "New York Post": "nypost.com",
  "New Zealand Herald": "nzherald.co.nz",
  "Newsday": "newsday.com",
  "Newslaundry": "newslaundry.com",
  "Newsweek": "newsweek.com",
  "Nikkei Asian Review": "asia.nikkei.com",
  "Nordwest Zeitung": "nwzonline.de",
  "NRC Handelsblad": "nrc.nl",
  "NSC Total": "nsctotal.com.br",
  "NyTeknik": "nyteknik.se",
  "O Estado de S. Paulo": "estadao.com.br",
  "O Globo (& Valor Econômico)": "globo.com",
  "Observador.pt": "observador.pt",
  "Oil & Gas Journal": "ogj.com",
  "OKO.press (PL)": "oko.press",
  "ON3 (fetch from archive.is)": "on3.com",
  "Ouest-France.fr (not subdomains)": "ouest-france.fr",
  "Outdoor Life": "outdoorlife.com",
  "Outlook Business": "outlookbusiness.com",
  "Outlook India": "outlookindia.com",
  "Palo Alto Online": "paloaltoonline.com",
  "Paris Match": "parismatch.com",
  "Passauer Neue Presse (fetch from archive.is)": "pnp.de",
  "Paste Magazine": "pastemagazine.com",
  "PhiloMag.com": "philomag.com",
  "PhiloMag.de": "philomag.de",
  "Philonomist": "philonomist.com",
  "Philosophy Now": "philosophynow.org",
  "Pittsburgh Post Gazette": "post-gazette.com",
  "Política Exterior": "politicaexterior.com",
  "Politico (regwall; not pro)": "politico.com",
  "Polityka.pl": "polityka.pl",
  "Popular Science": "popsci.com",
  "Pour l'Éco": "pourleco.com",
  "Pour la Science.fr": "pourlascience.fr",
  "Profil.at": "profil.at",
  "Project Syndicate": "project-syndicate.org",
  "Prospect Magazine": "prospectmagazine.co.uk",
  "Public.fr": "public.fr",
  "Público.es": "publico.es",
  "Puck.news (fetch from archive.is)": "puck.news",
  "Puls Biznesu": "pb.pl",
  "Quartz (newsletter)": "qz.com",
  "Quora": "quora.com",
  "Réforme.net": "reforme.net",
  "Reuters": "reuters.com",
  "Revista Oeste": "revistaoeste.com",
  "Revue Conflits": "revueconflits.com",
  "Revue21.fr": "revue21.fr",
  "Rotowire": "rotowire.com",
  "RugbyPass": "rugbypass.com",
  "S&P Global": "spglobal.com",
  "Sábado (not video)": "sabado.pt",
  "Scholastic": "scholastic.com",
  "Schweizer Monat": "schweizermonat.ch",
  "Science (free articles only)": "science.org",
  "Science & Vie": "science-et-vie.com",
  "ScienceNews.org": "sciencenews.org",
  "Sciences et Avenir": "sciencesetavenir.fr",
  "Scientific American": "scientificamerican.com",
  "Semana (CO)": "semana.com",
  "Sky.it (sport & tg24 only)": "sky.it",
  "Slate": "slate.com",
  "SlideShare": "slideshare.net",
  "SOFREP": "sofrep.com",
  "South China Morning Post": "scmp.com",
  "Southern Weekly (fetch from archive.is)": "infzm.com",
  "Spacenews": "spacenews.com",
  "Spektrum.de": "spektrum.de",
  "Sports Illustrated": "si.com",
  "Springer Medizin": "springermedizin.de",
  "Standardmedia.co.ke (text only)": "standardmedia.co.ke",
  "Star Tribune": "startribune.com",
  "StatNews (fetch from archive.is)": "statnews.com",
  "Stereogum (no comments)": "stereogum.com",
  "Stern.de (fetch from archive.is)": "stern.de",
  "Stock News": "stocknews.com",
  "Stratfor": "stratfor.com",
  "Study.com (only lessons; no videos)": "study.com",
  "Stylist.co.uk": "stylist.co.uk",
  "Suomen Sotilas": "suomensotilas.fi",
  "Süddeutsche Zeitung (fetch from archive.is)": "sueddeutsche.de",
  "Südkurier (fetch from archive.is)": "suedkurier.de",
  "Swarajyamag": "swarajyamag.com",
  "Tampa Bay Times": "tampabay.com",
  "Tech in Asia": "techinasia.com",
  "Telegraaf (fetch from archive.is)": "telegraaf.nl",
  "Télérama.fr": "telerama.fr",
  "Tes Magazine": "tes.com",
  "Texas Monthly": "texasmonthly.com",
  "The American Conservative": "theamericanconservative.com",
  "The American Interest": "the-american-interest.com",
  "The American Scholar": "theamericanscholar.org",
  "The Art Newspaper": "theartnewspaper.com",
  "The Atlanta Journal-Constitution": "ajc.com",
  "The Atlantic": "theatlantic.com",
  "The Baffler": "thebaffler.com",
  "The Baltimore Banner": "thebanner.com",
  "The Boston Globe": "bostonglobe.com",
  "The Business Journals (free articles only)": "bizjournals.com",
  "The Business of Fashion": "businessoffashion.com",
  "The Christian Science Monitor": "csmonitor.com",
  "The Columbian": "columbian.com",
  "The Critic": "thecritic.co.uk",
  "The Daily Beast": "thedailybeast.com",
  "The Dallas Morning News": "dallasnews.com",
  "The Diplomat": "thediplomat.com",
  "The Dispatch (not newsletters; do not block TinyPass-script externally)": "thedispatch.com",
  "The Economist": "economist.com",
  "The Financial Express": "financialexpress.com",
  "The Globe and Mail": "theglobeandmail.com",
  "The Hill": "thehill.com",
  "The Hill Times": "hilltimes.com",
  "The Hindu (not epaper)": "thehindu.com",
  "The Hindu BusinessLine (not epaper)": "thehindubusinessline.com",
  "The Indian Express": "indianexpress.com",
  "The Intercept (regwall)": "theintercept.com",
  "The Irish Examiner": "irishexaminer.com",
  "The Irish News": "irishnews.com",
  "The Irish Times": "irishtimes.com",
  "The Japan Times (do not block TinyPass-script externally)": "japantimes.co.jp",
  "The Jerusalem Post": "jpost.com",
  "The Lamp Magazine": "thelampmagazine.com",
  "The Lawyer (UK; not mda)": "thelawyer.com",
  "The Leaflet.in": "theleaflet.in",
  "The Logic.co (do not block TinyPass-script externally)": "thelogic.co",
  "The Market.ch": "themarket.ch",
  "The Nation": "thenation.com",
  "The New Atlantis": "thenewatlantis.com",
  "The New Criterion": "newcriterion.com",
  "The New Republic": "newrepublic.com",
  "The New Statesman": "newstatesman.com",
  "The New World (UK)": "thenewworld.co.uk",
  "The New York Review of Books": "nybooks.com",
  "The New York Sun (text only)": "nysun.com",
  "The New York Times": "nytimes.com",
  "The News Lens (JP)": "thenewslens.com",
  "The News Minute": "thenewsminute.com",
  "The Observer UK": "observer.co.uk",
  "The Past": "the-past.com",
  "The Philadelphia Inquirer": "inquirer.com",
  "The Point Magazine": "thepointmag.com",
  "The Quint": "thequint.com",
  "The San Francisco Standard": "sfstandard.com",
  "The Saturday Paper (AU)": "thesaturdaypaper.com.au",
  "The Scientist (archive)": "the-scientist.com",
  "The Seattle Times": "seattletimes.com",
  "The Spokesman-Review": "spokesman.com",
  "The Star.co.ke": "the-star.co.ke",
  "The Telegraph": "telegraph.co.uk",
  "The Times UK (fetch from archive.is)": "thetimes.com",
  "The Times Literary Supplement": "the-tls.com",
  "The Wall Street Journal": "wsj.com",
  "The Washington Post": "washingtonpost.com",
  "The Week (regwall)": "theweek.com",
  "The West Australian (+ regional/opt-in to custom sites)": "thewest.com.au",
  "The Wrap": "thewrap.com",
  "Times Higher Education": "timeshighereducation.com",
  "Tom's Hardware": "tomshardware.com",
  "Tuttosport": "tuttosport.com",
  "UnHerd": "unherd.com",
  "UOL.com.br": "uol.com.br",
  "USA Today": "usatoday.com",
  "Valeurs Actuelles (text only)": "valeursactuelles.com",
  "Vice": "vice.com",
  "Vibilagare.se": "vibilagare.se",
  "Vikatan": "vikatan.com",
  "Vogue Business": "voguebusiness.com",
  "Vorarlberg Nachrichten": "vn.at",
  "Vorarlberg Online": "vol.at",
  "Vrij Nederland": "vn.nl",
  "War on the Rocks": "warontherocks.com",
  "Washington Examiner": "washingtonexaminer.com",
  "Weltkunst": "weltkunst.de",
  "Weser-Kurier": "weser-kurier.de",
  "Winnipeg Free Press": "winnipegfreepress.com",
  "WirtschaftsWoche (text only & GST-link)": "wiwo.de",
  "Wonderzine": "wonderzine.com",
  "World Economics": "worldeconomics.com",
  "Ynet": "ynet.co.il",
  "Amp-access": "cdn.ampproject.org",
  "Amplitude": "amplitude.com",
  "BlueConic": "blueconic.net",
  "Cxense": "cxense.com",
  "Ensighten": "ensighten.com",
  "Evolok": "evolok.net",
  "FewCents": "fewcents.co",
  "MatherAnalytics": "matheranalytics.com",
  "NewsMemory": "newsmemory.com",
  "Memberstack": "memberstack.com",
  "Omeda Olytics": "omeda.com",
  "OneCount": "onecount.net",
  "Pelcro": "pelcro.com",
  "Piano.io (+ TinyPass)": "piano.io",
  "Pico.tools": "pico.tools",
  "Poool.fr": "poool.fr",
  "Qiota": "qiota.com",
  "Sophi.io": "sophi.io",
  "Steady": "steadyhq.com",
  "Zephr": "zephr.com"
};

var defaultDomains = Object.values(defaultSites).filter(domain => !domain.startsWith("###"));

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { defaultSites, defaultDomains };
}
