// sites.js
var defaultSites = {
  "60 Millions de consommateurs": "60millions-mag.com",
  "Aachener Zeitung (fetch from archive.is)": "aachener-zeitung.de",
  "Actu.fr": "actu.fr",
  "Adweek": "adweek.com",
  "Al-Monitor (fetch from archive.is)": "al-monitor.com",
  "Albuquerque Journal": "abqjournal.com",
  "Alternatives Economiques": "alternatives-economiques.fr",
  "Ámbito": "ambito.com",
  "America's Test Kitchen": "americastestkitchen.com",
  "American Affairs": "americanaffairsjournal.org",
  "American Banker": "americanbanker.com",
  "American Purpose": "americanpurpose.com",
  "Aoc.media": "aoc.media",
  "Artforum": "artforum.com",
  "Artnet": "artnet.com",
  "Atavist Magazine": "atavist.com",
  "Atlantico.fr": "atlantico.fr",
  "Autocar.co.uk": "autocar.co.uk",
  "Automobilwoche": "automobilwoche.de",
  "Axios": "axios.com",
  "Badische Neueste Nachrichten (fetch from archive.is)": "bnn.de",
  "Balkan Insight": "balkaninsight.com",
  "Barron's": "barrons.com",
  "BBC History Extra": "historyextra.com",
  "BBC USA": "bbc.com",
  "Benzinga": "benzinga.com",
  "Berliner Zeitung (fetch from archive.is)": "berliner-zeitung.de",
  "Bild (fetch from archive.is)": "bild.de",
  "Bloomberg (not Terminal)": "bloomberg.com",
  "Business Insider": "businessinsider.com",
  "Business Standard": "business-standard.com",
  "Capital.fr": "capital.fr",
  "CaravanMagazine.in (fetch from archive.is)": "caravanmagazine.in",
  "Challenges": "challenges.fr",
  "Chicago Sun-Times": "chicago.suntimes.com",
  "CNBC (news only)": "cnbc.com",
  "CNN": "cnn.com",
  "Corriere della Sera": "corriere.it",
  "Courrier international": "courrierinternational.com",
  "Der Spiegel (fetch from archive.is)": "spiegel.de",
  "Der Standard.at": "derstandard.at",
  "Der Tagesspiegel (fetch from archive.is)": "tagesspiegel.de",
  "Die Presse (AT)": "diepresse.com",
  "Die Welt (fetch from archive.is)": "welt.de",
  "Die Zeit (fetch from archive.is)": "zeit.de",
  "Discover Magazine": "discovermagazine.com",
  "El Confidencial": "elconfidencial.com",
  "El País": "elpais.com",
  "Entrepreneur": "entrepreneur.com",
  "ESPN USA (news only; fetch from archive.is)": "espn.com",
  "Fast Company": "fastcompany.com",
  "Financial Times": "ft.com",
  "Forbes": "forbes.com",
  "Foreign Affairs": "foreignaffairs.com",
  "Foreign Policy": "foreignpolicy.com",
  "Fortune": "fortune.com",
  "Frankfurter Allgemeine Zeitung": "faz.net",
  "Handelsblatt": "handelsblatt.com",
  "Harvard Business Review": "hbr.org",
  "Heise online (fetch from archive.is)": "heise.de",
  "Hindustan Times": "hindustantimes.com",
  "Inc.com": "inc.com",
  "India Today": "indiatoday.in",
  "Inside Higher Ed": "insidehighered.com",
  "Investor's Business Daily": "investors.com",
  "L'Équipe.fr": "lequipe.fr",
  "L'Express": "lexpress.fr",
  "La Nación": "lanacion.com.ar",
  "La Tercera": "latercera.com",
  "La Vanguardia": "lavanguardia.com",
  "Le Figaro": "lefigaro.fr",
  "Le Monde.fr": "lemonde.fr",
  "Le Parisien": "leparisien.fr",
  "Le Point": "lepoint.fr",
  "Les Échos": "lesechos.fr",
  "Libération.fr": "liberation.fr",
  "London Review of Books": "lrb.co.uk",
  "Los Angeles Times": "latimes.com",
  "MarketWatch": "marketwatch.com",
  "MIT Technology Review": "technologyreview.com",
  "National Geographic USA": "nationalgeographic.com",
  "National Review": "nationalreview.com",
  "Nature (fetch from archive.is)": "nature.com",
  "NBC News": "nbcnews.com",
  "Neue Zürcher Zeitung": "nzz.ch",
  "New Scientist": "newscientist.com",
  "New York Post": "nypost.com",
  "Newsweek": "newsweek.com",
  "Nikkei Asian Review": "asia.nikkei.com",
  "NRC Handelsblad": "nrc.nl",
  "Politico": "politico.com",
  "Project Syndicate": "project-syndicate.org",
  "Puck.news (fetch from archive.is)": "puck.news",
  "Quartz": "qz.com",
  "Reuters": "reuters.com",
  "Scientific American": "scientificamerican.com",
  "Slate": "slate.com",
  "South China Morning Post": "scmp.com",
  "Sports Illustrated": "si.com",
  "Star Tribune": "startribune.com",
  "StatNews (fetch from archive.is)": "statnews.com",
  "Süddeutsche Zeitung (fetch from archive.is)": "sueddeutsche.de",
  "Tech in Asia": "techinasia.com",
  "Telegraaf (fetch from archive.is)": "telegraaf.nl",
  "The American Conservative": "theamericanconservative.com",
  "The Atlantic": "theatlantic.com",
  "The Boston Globe": "bostonglobe.com",
  "The Daily Beast": "thedailybeast.com",
  "The Economist": "economist.com",
  "The Globe and Mail": "theglobeandmail.com",
  "The Hindu": "thehindu.com",
  "The Indian Express": "indianexpress.com",
  "The Irish Times": "irishtimes.com",
  "The Japan Times": "japantimes.co.jp",
  "The New Republic": "newrepublic.com",
  "The New York Review of Books": "nybooks.com",
  "The New York Times": "nytimes.com",
  "The Philadelphia Inquirer": "inquirer.com",
  "The Seattle Times": "seattletimes.com",
  "The Telegraph": "telegraph.co.uk",
  "The Times UK (fetch from archive.is)": "thetimes.com",
  "The Wall Street Journal": "wsj.com",
  "The Washington Post": "washingtonpost.com",
  "Time": "time.com",
  "USA Today": "usatoday.com",
  "Vice": "vice.com",
  "Vogue Business": "voguebusiness.com",
  "Wired": "wired.com"
};

var defaultDomains = Object.values(defaultSites).filter(domain => !domain.startsWith("###"));

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { defaultSites, defaultDomains };
}
